config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :activity_processes
  resources :selective_processes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root  'welcome#home'

  get "home/logout"
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/welcome/about',   to: 'welcome#about',   via: 'get'
  match '/rpg',     to: 'rpg#index', via: 'get'
  match '/rpg/index', to: 'rpg#show', via: 'get'
  match '/index', to: 'welcome#index', via: 'get'
  match '/atividades/criar/:id' => 'activity_processes#new_process_defined', :as => :atividade_criar, :via => :get

  get '/signup',  to: 'users#new'
  get '/processos', to: 'selective_processes#index'
  get '/processos/show/editar/:id', to: 'selective_processes#show_edit'
  get '/processos/show/excluir/:id', to: 'selective_processes#show_delete'
  get '/processos/criar', to: 'selective_processes#new'
  get "/processos/editar", to: 'selective_processes#index_edit'
  get "/processos/excluir", to: 'selective_processes#index_delete'
  get '/atividades', to: 'activity_processes#index'
  get '/atividades/criar', to: 'activity_processes#new'
  get '/atividades/:id', to: 'activity_processes#show'

end

app/controllers/activity_processes_controller.rb
class ActivityProcessesController < ApplicationController
  before_action :set_activity_process, only: [:show, :edit, :update, :destroy]

  # GET /activity_processes
  # GET /activity_processes.json
  def index
    @activity_processes = ActivityProcess.all
  end

  # GET /activity_processes/1
  # GET /activity_processes/1.json
  def show
    @activity_process = ActivityProcess.find(params[:id])
    @process = SelectiveProcess.find(@activity_process.SelectiveProcess_id)
    @feedback = Feedback.new
    @feedbacks = Feedback.where(["ActivityProcess_id = ? ", @activity_process.id])

  end

  # GET /activity_processes/new
  def new
    @activity_process = ActivityProcess.new
   
  end

  def new_process_defined
     @activity_process = ActivityProcess.new
     @selective_process = SelectiveProcess.find(params[:id])
  end

  # GET /activity_processes/1/edit
  def edit
  end

  # POST /activity_processes
  # POST /activity_processes.json
  def create
    @activity_process = ActivityProcess.new(activity_process_params)

    respond_to do |format|
      if @activity_process.save
        format.html { redirect_to @activity_process, notice: 'Atividade criada com sucesso.' }
        format.json { render :show, status: :created, location: @activity_process }
      else
        format.html { render :new }
        format.json { render json: @activity_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_processes/1
  # PATCH/PUT /activity_processes/1.json
  def update
    respond_to do |format|
      if @activity_process.update(activity_process_params)
        format.html { redirect_to @activity_process, notice: 'Atividade atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @activity_process }
      else
        format.html { render :edit }
        format.json { render json: @activity_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_processes/1
  # DELETE /activity_processes/1.json
  def destroy
    @activity_process.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Atividade excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_process
      @activity_process = ActivityProcess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_process_params
      params.require(:activity_process).permit(:SelectiveProcess_id, :name_activity, :responsible_activity, :description_activity, :deadline_activity)
    end
end

app/helpers/activity_processes_helper.rb
module ActivityProcessesHelper
end

app/views/activity_processes/_form.html.erb
<%= form_for(@activity_process) do |f| %>
  <div class="container">
  <% if @activity_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_process.errors.count, "Erro") %> Atividade não pode ser criada:</h2>

      <ul>
      <% @activity_process.errors.each do |attr,msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
  <div class="container">
  <div class="field">
    <%= f.label :nome_da_atividade %><br>
    <%= f.text_field :name_activity %>
  </div>
  <div class="field">
    <%= f.label :processo_da_atividade %><br>
    <%= f.collection_select :SelectiveProcess_id, SelectiveProcess.all, :id, :name_process, :prompt => "Selecione um Processo" %><br>
  </div> 
  <div class="field">
    <%= f.label :responsavel %><br>
    <%= f.collection_select :responsible_activity, User.all, :id, :name, :prompt => "Selecione um responsável" %><br>
  </div>
  <div class="field">
    <%= f.label :descrição %><br>
    <%= f.text_area :description_activity %><br>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline_activity %>
  </div>
  <div class="actions">
    <%= f.submit :"Criar Atividade", class: "btn btn-success btn-md", style: "color:white;  float: left"%>
  </div>
<% end %>
<%= link_to 'Voltar', root_path, class: "btn btn-warning btn-md", style: "color:white; margin-left:1%;" %>
</div>

app/views/activity_processes/_form_feedback.erb
<%= form_for Feedback.new do |f| %>

  <div class="field">
    <%= f.text_field :subject, :value => "Assunto"%>
  </div>
  <div class="field">
    <%= f.text_area :content, :value => "Comentário..."%>
  </div>

  <div class="field" style = "display:none;">
    <%= f.label :Atividade %><br>
    <%= f.text_field :ActivityProcess_id, :value => @activity_process.id %>
  </div>

  <div class="actions">
    <%= f.submit :"Enviar", class: "btn btn-success btn-md", style: "color:white; float:left; margin-top:0.9%;margin-right:1%;"%>
  </div>



<% end %>

app/views/activity_processes/_form_process_defined.html.erb
<%= form_for(@activity_process) do |f| %>
  <div class="container">
  <% if @activity_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_process.errors.count, "Erro") %> Atividade não pode ser criada:</h2>

      <ul>
      <% @activity_process.errors.each do |attr,msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
  <div class="container">
  <div class="field">
    <%= f.label :nome_da_atividade %><br>
    <%= f.text_field :name_activity %>
  </div>
  <div class="field">
    <%= f.label :processo_da_atividade %><br>
    <%= "#{@selective_process.name_process}" %><br>
  </div> 
  <div class="field" style = "display:none;">
    <%= f.label :processo_da_atividade %><br>
    <%= f.text_field :SelectiveProcess_id, :value => @selective_process.id %>
  </div>
  <div class="field">
    <%= f.label :responsavel %><br>
    <%= f.collection_select :responsible_activity, User.all, :id, :name, :prompt => "Selecione um responsável" %><br>
  </div>
  <div class="field">
    <%= f.label :descrição %><br>
    <%= f.text_area :description_activity %><br>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline_activity %>
  </div>
  <div class="actions">
    <%= f.submit :"Confirmar", class: "btn btn-success btn-md", style: "color:white;  float: left"%>
  </div>
<% end %>
<%= link_to 'Voltar', root_path, class: "btn btn-warning btn-md", style: "color:white; margin-left:1%;" %>
</div>

app/views/activity_processes/edit.html.erb
<div class="container">
  <center>
    <div class="jumbotron">
    
     <div class ="row">
<h1>Editar Atividade</h1>
</div>
</div>
</center>
<%= render 'form' %>
</div>

app/views/activity_processes/index.html.erb
<h1>Lista de Atividades do Processo</h1>

<table>
  <thead>
    <tr>
      <th>Processo</th>
      <th>Nome da Atividade</th>
      <th>Responsável pela Atividade</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_processes.each do |activity_process| %>
      <% @process = SelectiveProcess.find(activity_process.SelectiveProcess_id) %>
      <tr>
        <td><%= @process.name_process %></td>
        <td><%= activity_process.name_activity %></td>
        <td><%= activity_process.responsible_activity %></td>
        <td><%= activity_process.deadline_activity %></td>
        <td><%= link_to 'Ver', activity_process %></td>
        <% if current_user.is_admin %>
         <!-- <td><%= link_to 'Editar', edit_activity_process_path(activity_process) %></td>-->
          <td><%= link_to 'Excluir', activity_process, method: :delete, data: { confirm: 'Tem certeza que deseja excluir essa atividade?' } %></td>
        <% else %>
          <% #Do nothing %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.is_admin %>
  <%= link_to 'Nova Atividade', new_activity_process_path %>
<% else %>
  <% # do nothing %>
<% end %>

app/views/activity_processes/new.html.erb
<div class="container">
	<center>
	<div class="jumbotron">
		
	<div class ="row">
<h1>Nova Atividade</h1>
</div>
</div>
</center>
</div>

<%= render 'form' %>

app/views/activity_processes/new_process_defined.html.erb
<div class="container">
	<center>
	<div class="jumbotron">
		
	<div class ="row">
<h1>Nova Atividade</h1>
</div>
</div>
</center>
</div>

<%= render 'form_process_defined' %>

app/views/activity_processes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  
    <div class="jumbotron">
    
     <div class ="row">
      <center>

        <h1><%= @activity_process.name_activity %></h1 >
           </center>
          <p>
            <strong>Processo:</strong>
            <%=@process.name_process%>
          </p>
            <p>
              <% @responsible_actvity = User.find(@activity_process.responsible_activity) %>
              <strong>Responsável:</strong>
              <%= @responsible_actvity.name %>
            </p>

            <p>
              <strong>Deadline:</strong>
              <%= @activity_process.deadline_activity %>
            </p>
            <p>
            <strong>Descrição:</strong>
            <p><%= @activity_process.description_activity %></p>
          </p>
          </div>
         </div>

<div = "row">
<center>
  <h3>Comentários</h3>
  
<% @feedbacks.each do |feedback| %>
</center>
 <div class="panel panel-primary">

      <div class="panel-heading"><strong><center><%= feedback.author%>: </strong><%= feedback.subject%></center></div>
      
      <div class="panel-body"><%= feedback.content %></div>
  </div>

<% end %>
</center>
<h3>Comentar</h3>
<%= render 'form_feedback' %>
<%= link_to 'Voltar', "/selective_processes/#{@activity_process.SelectiveProcess_id}", class: "btn btn-warning btn-md", style: "color:white;" %>

</div>
</div>


           