config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :activity_processes
  resources :selective_processes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root  'welcome#home'

  get "home/logout"
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/welcome/about',   to: 'welcome#about',   via: 'get'
  match '/rpg',     to: 'rpg#index', via: 'get'
  match '/rpg/index', to: 'rpg#show', via: 'get'
  match '/index', to: 'welcome#index', via: 'get'
  match '/atividades/criar/:id' => 'activity_processes#new_process_defined', :as => :atividade_criar, :via => :get

  get '/signup',  to: 'users#new'
  get '/processos', to: 'selective_processes#index'
  get '/processos/show/editar/:id', to: 'selective_processes#show_edit'
  get '/processos/show/excluir/:id', to: 'selective_processes#show_delete'
  get '/processos/criar', to: 'selective_processes#new'
  get "/processos/editar", to: 'selective_processes#index_edit'
  get "/processos/excluir", to: 'selective_processes#index_delete'
  get '/atividades', to: 'activity_processes#index'
  get '/atividades/criar', to: 'activity_processes#new'
  get '/atividades/:id', to: 'activity_processes#show'

end

app/controllers/selective_processes_controller.rb
class SelectiveProcessesController < ApplicationController
  before_action :set_selective_process, only: [:show, :edit, :update, :destroy]

  # GET /selective_processes
  # GET /selective_processes.json
  def index
    @selective_processes = SelectiveProcess.all
  end

  def index_edit
    @selective_processes = SelectiveProcess.all
  end

  def index_delete
    @selective_processes = SelectiveProcess.all
  end

  # GET /selective_processes/1
  # GET /selective_processes/1.json
  def show
    @selective_process = SelectiveProcess.find(params[:id])
    @responsible = User.find(@selective_process.responsible)
    @activities = @selective_process.get_activities
  end

  def show_edit
    @selective_process = SelectiveProcess.find(params[:id])
    @responsible = User.find(@selective_process.responsible)
    @activities = @selective_process.get_activities
  end

  def show_delete
    @selective_process = SelectiveProcess.find(params[:id])
    @responsible = User.find(@selective_process.responsible)
    @activities = @selective_process.get_activities
  end

  # GET /selective_processes/new
  def new
    @selective_process = SelectiveProcess.new
  end

  # GET /selective_processes/1/edit
  def edit
    @selective_process = SelectiveProcess.find(params[:id])
  end

  # POST /selective_processes
  # POST /selective_processes.json
  def create
    @selective_process = SelectiveProcess.new(selective_process_params)

    respond_to do |format|
      if @selective_process.save
        format.html { redirect_to @selective_process, notice: 'Processo criado com sucesso.' }
        format.json { render :show, status: :created, location: @selective_process }
      else
        format.html { render :new }
        format.json { render json: @selective_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selective_processes/1
  # PATCH/PUT /selective_processes/1.json
  def update
    respond_to do |format|
      if @selective_process.update(selective_process_params)
        format.html { redirect_to @selective_process, notice: 'Processo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @selective_process }
      else
        format.html { render :edit }
        format.json { render json: @selective_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selective_processes/1
  # DELETE /selective_processes/1.json
  def destroy
    @selective_process.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Prcoesso deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selective_process
      @selective_process = SelectiveProcess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selective_process_params
      params.require(:selective_process).permit(:name_process, :responsible, :deadline)
    end
end

app/helpers/selective_processes_helper.rb
module SelectiveProcessesHelper
end

app/views/selective_processes/_form.html.erb
<%= form_for(@selective_process) do |f| %>
  <div class="container">
  <% if @selective_process.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selective_process.errors.count, "Erro") %> Processo não pode ser criado:</h2>

      <ul>
      <% @selective_process.errors.each do |attr,msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
  <div class="container">
  <div class="field">
    <%= f.label :nome_do_processo %><br>
    <%= f.text_field :name_process %>
  </div>
  <div class="field">
    <%= f.label :responsavel %><br>
    <%= f.collection_select :responsible, User.all, :id, :name, :prompt => "Selecione um responsável" %><br>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="actions">
    <%= f.submit :"Confirmar", class: "btn btn-success btn-md", style: "color:white;  float: left"%>
  </div>
<% end %>
<%= link_to 'Voltar', root_path, class: "btn btn-warning btn-md", style: "color:white; margin-left:1%;" %>
</div>

app/views/selective_processes/edit.html.erb
<div class="container">
  <center>
    <div class="jumbotron">
    
     <div class ="row">
	<h1>Editar Processo</h1>
	</div>
</div>
</center>
<div class ="row">
<div class="container">

	<%= link_to "Criar Atividade", atividade_criar_path(@selective_process),class: "btn btn-success btn-sm", style: "color:white" %>

	<%= link_to "Editar Atividade", "/processos/show/editar/#{@selective_process.id}" ,class: "btn btn-warning btn-sm", style: "color:white" %>

	<%= link_to "Excluir Atividade", "/processos/show/excluir/#{@selective_process.id}",class: "btn btn-danger btn-sm", style: "color:white" %>
</br>
</br>
</div>
<%= render 'form' %>

</div>

app/views/selective_processes/index.html.erb
<div class="container">
  <center>
    <div class="jumbotron">
    
     <div class ="row">
      <h1>Lista de Processos</h1>
      </div>
    </div>
    </center>
  </div>
    <div class="container">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nome do processo</th>
              <th>Responsável</th>
              <th>Deadline</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @selective_processes.each do |selective_process| %>
              <% @responsible = User.find(selective_process.responsible) %>
              <tr>
                <td><%= selective_process.name_process %></td>
                <td><%= @responsible.name %></td>
                <td><%= selective_process.deadline %></td>
                <td><%= link_to 'Ver', selective_process, class: "btn btn-info btn-xs", style: "color:white; text-decoration:none;" %></td>
                <% if current_user.is_admin %>
                  <!--<td><%= link_to 'Editar', edit_selective_process_path(selective_process),class: "btn btn-warning btn-xs", style: "color:white; text-decoration:none;"%></td>-->
                  <td><%= link_to 'Excluir', selective_process, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse processo?' }, class: "btn btn-danger btn-xs", style: "color:white; text-decoration:none;" %></td>
                <% else %>
                  <% # do nothing %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        </br>
        </br>
        </br>
        </br>
         <center>
           <%= link_to 'Voltar', root_path, class: "btn btn-warning btn-md", style: "color:white;" %>
          </center>
      </div>

    </div>

  </div>

app/views/selective_processes/index_delete.html.erb
<div class="container">
  <center>
    <div class="jumbotron">
    
     <div class ="row">
      <h1>Lista de Processos</h1>
      </div>
    </div>
    </center>
  </div>
    <div class="container">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nome do processo</th>
              <th>Responsável</th>
              <th>Deadline</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @selective_processes.each do |selective_process| %>
              <% @responsible = User.find(selective_process.responsible) %>
              <tr>
                <td><%= selective_process.name_process %></td>
                <td><%= @responsible.name %></td>
                <td><%= selective_process.deadline %></td>
                <% if current_user.is_admin %>
                  <td><%= link_to 'Excluir', selective_process, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse processo?' }, class: "btn btn-danger btn-xs", style: "color:white; text-decoration:none;" %></td>
                <% else %>
                  <% # do nothing %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        </br>
        </br>
        </br>
        </br>
         <center>
           <%= link_to 'Voltar', root_path, class: "btn btn-warning btn-md", style: "color:white;" %>
          </center>
      </div>

    </div>

  </div>

app/views/selective_processes/index_edit.html.erb
<div class="container">
  <center>
    <div class="jumbotron">
    
     <div class ="row">
      <h1>Lista de Processos</h1>
      </div>
    </div>
    </center>
  </div>
    <div class="container">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nome do processo</th>
              <th>Responsável</th>
              <th>Deadline</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @selective_processes.each do |selective_process| %>
              <% @responsible = User.find(selective_process.responsible) %>
              <tr>
                <td><%= selective_process.name_process %></td>
                <td><%= @responsible.name %></td>
                <td><%= selective_process.deadline %></td>
                <% if current_user.is_admin %>
                  <td><%= link_to 'Editar', edit_selective_process_path(selective_process),class: "btn btn-warning btn-xs", style: "color:white; text-decoration:none;"%></td>
                <% else %>
                  <% # do nothing %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        </br>
        </br>
        </br>
        </br>
         <center>
           <%= link_to 'Voltar', root_path, class: "btn btn-warning btn-md", style: "color:white;" %>
          </center>
      </div>

    </div>

  </div>

app/views/selective_processes/new.html.erb
<div class="container">
	<center>
	<div class="jumbotron">
		
	<div class ="row">
<h1>Novo Processo</h1>
</div>
</div>
</center>
</div>

<%= render 'form' %>

app/views/selective_processes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  
    <div class="jumbotron">
    
     <div class ="row">
      <center>
      <h1><%= @selective_process.name_process %></h1>
  
<p>
  <strong>Responsável:</strong>
  <%= @responsible.name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @selective_process.deadline %>
</p>
</center>
</div>
</div>

  <center>
	<strong><h3>Atividades</h3></strong>
  </center>
  <div class="container">
  <table class="table table-striped">
          <thead>
            <tr>
              <th>Nome da Atividade</th>
              <th>Responsável</th>
              <th>Deadline</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @activities.each do |activity| %>
              <% @responsible_actvity = User.find(activity.responsible_activity) %>
              <tr>
                <td><%= activity.name_activity %></td>
                <td><%= @responsible_actvity.name %></td>
                <td><%= activity.deadline_activity %></td>
                <td><%= link_to 'Ver', activity, class: "btn btn-info btn-xs", style: "color:white; text-decoration:none;" %></td>
                <% if current_user.is_admin %>
                  <!--<td><%= link_to 'Editar', edit_activity_process_path(activity),class: "btn btn-warning btn-xs", style: "color:white; text-decoration:none;"%></td>-->
                  <td><%= link_to 'Excluir', activity, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs", style: "color:white; text-decoration:none;" %></td>
                <% else %>
                  <% # do nothing %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        </br>
        </br>
        </br>
        </br>
        
</div>  
<center>
        <%= link_to 'Voltar', "/processos", class: "btn btn-warning btn-md", style: "color:white;" %>
      </center>

app/views/selective_processes/show_delete.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  
    <div class="jumbotron">
    
     <div class ="row">
      <center>
      <h1><%= @selective_process.name_process %></h1>
  
<p>
  <strong>Responsável:</strong>
  <%= @responsible.name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @selective_process.deadline %>
</p>
</center>
</div>
</div>

  <center>
	<strong><h3>Atividades</h3></strong>
  </center>
  <div class="container">
  <table class="table table-striped">
          <thead>
            <tr>
              <th>Nome da Atividade</th>
              <th>Responsável</th>
              <th>Deadline</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @activities.each do |activity| %>
              <% @responsible_actvity = User.find(activity.responsible_activity) %>
              <tr>
                <td><%= activity.name_activity %></td>
                <td><%= @responsible_actvity.name %></td>
                <td><%= activity.deadline_activity %></td>
                <% if current_user.is_admin %>
                  <td><%= link_to 'Excluir', activity, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs", style: "color:white; text-decoration:none;" %></td>
                <% else %>
                  <% # do nothing %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        </br>
        </br>
        </br>
        </br>
        
</div>  
<center>
        <%= link_to 'Voltar', "/processos", class: "btn btn-warning btn-md", style: "color:white;" %>
      </center>

app/views/selective_processes/show_edit.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  
    <div class="jumbotron">
    
     <div class ="row">
      <center>
      <h1><%= @selective_process.name_process %></h1>
  
<p>
  <strong>Responsável:</strong>
  <%= @responsible.name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @selective_process.deadline %>
</p>
</center>
</div>
</div>

  <center>
	<strong><h3>Atividades</h3></strong>
  </center>
  <div class="container">
  <table class="table table-striped">
          <thead>
            <tr>
              <th>Nome da Atividade</th>
              <th>Responsável</th>
              <th>Deadline</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @activities.each do |activity| %>
              <% @responsible_actvity = User.find(activity.responsible_activity) %>
              <tr>
                <td><%= activity.name_activity %></td>
                <td><%= @responsible_actvity.name %></td>
                <td><%= activity.deadline_activity %></td>
                <% if current_user.is_admin %>
                  <td><%= link_to 'Editar', edit_activity_process_path(activity),class: "btn btn-warning btn-xs", style: "color:white; text-decoration:none;"%>
                <% else %>
                  <% # do nothing %>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        </br>
        </br>
        </br>
        </br>
        
</div>  
<center>
        <%= link_to 'Voltar', "/processos", class: "btn btn-warning btn-md", style: "color:white;" %>
      </center>