config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :activity_processes
  resources :selective_processes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root  'welcome#home'

  get "home/logout"
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/welcome/about',   to: 'welcome#about',   via: 'get'
  match '/rpg',     to: 'rpg#index', via: 'get'
  match '/rpg/index', to: 'rpg#show', via: 'get'
  match '/index', to: 'welcome#index', via: 'get'
  match '/atividades/criar/:id' => 'activity_processes#new_process_defined', :as => :atividade_criar, :via => :get

  get '/signup',  to: 'users#new'
  get '/processos', to: 'selective_processes#index'
  get '/processos/show/editar/:id', to: 'selective_processes#show_edit'
  get '/processos/show/excluir/:id', to: 'selective_processes#show_delete'
  get '/processos/criar', to: 'selective_processes#new'
  get "/processos/editar", to: 'selective_processes#index_edit'
  get "/processos/excluir", to: 'selective_processes#index_delete'
  get '/atividades', to: 'activity_processes#index'
  get '/atividades/criar', to: 'activity_processes#new'
  get '/atividades/:id', to: 'activity_processes#show'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base

	belongs_to :activity_process

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/criar
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)
    @feedback.author = current_user.name
    respond_to do |format|
      if @feedback.save
        format.html { redirect_to "/activity_processes/#{@feedback.ActivityProcess_id}", notice: '' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:subject, :content, :ActivityProcess_id)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :Atividade %><br>
    <%= f.text_field :ActivityProcess_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Content</th>
      <th>id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.subject %></td>
        <td><%= feedback.content %></td>
        <td><%= feedback.ActivityProcess_id %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @feedback.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @feedback.content %>
</p>
<strong>atividade:</strong>
  <%= @feedback.ActivityProcess_id %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>